const db = require("./database");

const products = [
  // Drinks
  {
    product_id: "DR001",
    name: "Coke 600ml",
    category: "Drinks",
    cost_price: 2,
    sale_price: 4,
    initial_quantity: 100,
    perishable: 0,
    shelf_life_days: null,
  },
  {
    product_id: "DR002",
    name: "Pepsi 600ml",
    category: "Drinks",
    cost_price: 2,
    sale_price: 4,
    initial_quantity: 100,
    perishable: 0,
    shelf_life_days: null,
  },
  {
    product_id: "DR003",
    name: "Minute Maid 600ml",
    category: "Drinks",
    cost_price: 2,
    sale_price: 4,
    initial_quantity: 100,
    perishable: 0,
    shelf_life_days: null,
  },
  {
    product_id: "DR004",
    name: "Schweppes Soda Water 600ml",
    category: "Drinks",
    cost_price: 2,
    sale_price: 4,
    initial_quantity: 100,
    perishable: 0,
    shelf_life_days: null,
  },
  {
    product_id: "DR005",
    name: "Solo 600ml",
    category: "Drinks",
    cost_price: 2,
    sale_price: 4,
    initial_quantity: 100,
    perishable: 0,
    shelf_life_days: null,
  },

  // Frozen
  {
    product_id: "FR001",
    name: "Peas",
    category: "Frozen",
    cost_price: 3,
    sale_price: 6,
    initial_quantity: 40,
    perishable: 1,
    shelf_life_days: 180,
  },
  {
    product_id: "FR002",
    name: "Nuggets",
    category: "Frozen",
    cost_price: 5,
    sale_price: 10,
    initial_quantity: 50,
    perishable: 1,
    shelf_life_days: 180,
  },
  {
    product_id: "FR003",
    name: "TV Dinner",
    category: "Frozen",
    cost_price: 4,
    sale_price: 8,
    initial_quantity: 40,
    perishable: 1,
    shelf_life_days: 120,
  },
  {
    product_id: "FR004",
    name: "Burrito",
    category: "Frozen",
    cost_price: 3.5,
    sale_price: 7,
    initial_quantity: 40,
    perishable: 1,
    shelf_life_days: 120,
  },
  {
    product_id: "FR005",
    name: "Blueberries",
    category: "Frozen",
    cost_price: 4,
    sale_price: 8,
    initial_quantity: 30,
    perishable: 1,
    shelf_life_days: 180,
  },

  // Snacks
  {
    product_id: "SN001",
    name: "KitKat",
    category: "Snacks",
    cost_price: 1,
    sale_price: 2.5,
    initial_quantity: 100,
    perishable: 0,
    shelf_life_days: null,
  },
  {
    product_id: "SN002",
    name: "Pringles",
    category: "Snacks",
    cost_price: 2.5,
    sale_price: 5.5,
    initial_quantity: 80,
    perishable: 0,
    shelf_life_days: null,
  },
  {
    product_id: "SN003",
    name: "Popcorn",
    category: "Snacks",
    cost_price: 1.5,
    sale_price: 3.5,
    initial_quantity: 60,
    perishable: 0,
    shelf_life_days: null,
  },
  {
    product_id: "SN004",
    name: "Tim Tam Original",
    category: "Snacks",
    cost_price: 2.5,
    sale_price: 5,
    initial_quantity: 70,
    perishable: 0,
    shelf_life_days: null,
  },
  {
    product_id: "SN005",
    name: "Doritos",
    category: "Snacks",
    cost_price: 2,
    sale_price: 4.5,
    initial_quantity: 80,
    perishable: 0,
    shelf_life_days: null,
  },
  // Dairy
  {
    product_id: "DY001",
    name: "Full Cream Milk 1L",
    category: "Dairy",
    cost_price: 2.5,
    sale_price: 4.5,
    initial_quantity: 50,
    perishable: 1,
    shelf_life_days: 21,
  },
  {
    product_id: "DY002",
    name: "Soy Milk 1L",
    category: "Dairy",
    cost_price: 2.8,
    sale_price: 5,
    initial_quantity: 40,
    perishable: 1,
    shelf_life_days: 30,
  },
  {
    product_id: "DY003",
    name: "Skim Milk 1L",
    category: "Dairy",
    cost_price: 2.5,
    sale_price: 4.5,
    initial_quantity: 40,
    perishable: 1,
    shelf_life_days: 21,
  },
  {
    product_id: "DY004",
    name: "Almond Milk 1L",
    category: "Dairy",
    cost_price: 3,
    sale_price: 5.5,
    initial_quantity: 40,
    perishable: 1,
    shelf_life_days: 30,
  },
  {
    product_id: "DY005",
    name: "Chocolate Milk 1L",
    category: "Dairy",
    cost_price: 2.8,
    sale_price: 5,
    initial_quantity: 40,
    perishable: 1,
    shelf_life_days: 14,
  },
  // Canned
  {
    product_id: "CN001",
    name: "Beans",
    category: "Canned",
    cost_price: 1,
    sale_price: 2.5,
    initial_quantity: 60,
    perishable: 0,
    shelf_life_days: null,
    },
  {
    product_id: "CN002",
    name: "Chickpeas",
    category: "Canned",
    cost_price: 1,
    sale_price: 2.5,
    initial_quantity: 60,
    perishable: 0,
    shelf_life_days: null,
  },
  { 
    product_id: "CN003",
    name: "Tuna",
    category: "Canned",
    cost_price: 1.8,
    sale_price: 4,
    initial_quantity: 60,
    perishable: 0,
    shelf_life_days: null,
  },
  {
    product_id: "CN004",
    name: "Soup",
    category: "Canned",
    cost_price: 1.5,
    sale_price: 3.5,
    initial_quantity: 50,
    perishable: 0,
    shelf_life_days: null,
  },
  {
    product_id: "CN005",
    name: "Spam",
    category: "Canned",
    cost_price: 2.5,
    sale_price: 5,
    initial_quantity: 40,
    perishable: 0,
    shelf_life_days: null,
  },
  // Household
  {
    product_id: "HH001",
    name: "Dishwashing Liquid",
    category: "Household",
    cost_price: 3,
    sale_price: 6,
    initial_quantity: 30,
    perishable: 0,
    shelf_life_days: null,
  },
  {
    product_id: "HH002",
    name: "Laundry Detergent",
    category: "Household",
    cost_price: 5,
    sale_price: 10,
    initial_quantity: 25,
    perishable: 0,
    shelf_life_days: null,
  },
  {
    product_id: "HH003",
    name: "Paper Towels",
    category: "Household",
    cost_price: 2.5,
    sale_price: 5,
    initial_quantity: 40,
    perishable: 0,
    shelf_life_days: null,
  },
  {
    product_id: "HH004",
    name: "Garbage Bags",
    category: "Household",
    cost_price: 2,
    sale_price: 4.5,
    initial_quantity: 30,
    perishable: 0,
    shelf_life_days: null,
  },
  {
    product_id: "HH005",
    name: "Surface Cleaner",
    category: "Household",
    cost_price: 3.5,
    sale_price: 7,
    initial_quantity: 25,
    perishable: 0,
    shelf_life_days: null,
  },
  // Personal Care
  {
    product_id: "PC001",
    name: "Toothpaste",
    category: "Personal Care",
    cost_price: 2.5,
    sale_price: 5,
    initial_quantity: 40,
    perishable: 0,
    shelf_life_days: null,
  },
  {
    product_id: "PC002",
    name: "Deodorant",
    category: "Personal Care",
    cost_price: 3,
    sale_price: 6,
    initial_quantity: 35,
    perishable: 0,
    shelf_life_days: null,
  },
  {
    product_id: "PC003",
    name: "Shampoo",
    category: "Personal Care",
    cost_price: 4,
    sale_price: 8,
    initial_quantity: 30,
    perishable: 0,
    shelf_life_days: null,
  },
  {
    product_id: "PC004",
    name: "Soap",
    category: "Personal Care",
    cost_price: 1.5,
    sale_price: 3.5,
    initial_quantity: 50,
    perishable: 0,
    shelf_life_days: null,
  },
  {
    product_id: "PC005",
    name: "Conditioner",
    category: "Personal Care",
    cost_price: 4,
    sale_price: 8,
    initial_quantity: 30,
    perishable: 0,
    shelf_life_days: null,
  },
  // Vegetables
  {
    product_id: "VG001",
    name: "Broccoli",
    category: "Vegetables",
    cost_price: 1.5,
    sale_price: 3,
    initial_quantity: 40,
    perishable: 1,
    shelf_life_days: 7,
  },
  {
    product_id: "VG002",
    name: "Carrots",
    category: "Vegetables",
    cost_price: 1,
    sale_price: 2.5,
    initial_quantity: 50,
    perishable: 1,
    shelf_life_days: 14,
  },
  {
    product_id: "VG003",
    name: "Lettuce",
    category: "Vegetables",
    cost_price: 1.5,
    sale_price: 3.5,
    initial_quantity: 40,
    perishable: 1,
    shelf_life_days: 5,
  },
  {
    product_id: "VG004",
    name: "Radish",
    category: "Vegetables",
    cost_price: 1.2,
    sale_price: 3,
    initial_quantity: 30,
    perishable: 1,
    shelf_life_days: 10,
  },
  {
    product_id: "VG005",
    name: "Cabbage",
    category: "Vegetables",
    cost_price: 2,
    sale_price: 4.5,
    initial_quantity: 30,
    perishable: 1,
    shelf_life_days: 14,
  },
  // Ready-to-Eat Meals
  {
    product_id: "RM001",
    name: "Sandwich",
    category: "Ready-to-Eat Meals",
    cost_price: 3,
    sale_price: 6.5,
    initial_quantity: 50,
    perishable: 1,
    shelf_life_days: 3,
  },
  {
    product_id: "RM002",
    name: "Meat Pie",
    category: "Ready-to-Eat Meals",
    cost_price: 2.5,
    sale_price: 5.5,
    initial_quantity: 50,
    perishable: 1,
    shelf_life_days: 2,
  },
  {
    product_id: "RM003",
    name: "Sushi Pack",
    category: "Ready-to-Eat Meals",
    cost_price: 4,
    sale_price: 8.5,
    initial_quantity: 40,
    perishable: 1,
    shelf_life_days: 3,
  },
  {
    product_id: "RM004",
    name: "Chicken Wrap",
    category: "Ready-to-Eat Meals",
    cost_price: 3.5,
    sale_price: 7.5,
    initial_quantity: 40,
    perishable: 1,
    shelf_life_days: 5,
  },
  {
    product_id: "RM005",
    name: "Sausage Roll",
    category: "Ready-to-Eat Meals",
    cost_price: 2.5,
    sale_price: 5.5,
    initial_quantity: 50,
    perishable: 1,
    shelf_life_days: 5,
  },
];

products.forEach((product) => {
  db.run(
    `
    INSERT INTO products (
      product_id,
      name,
      category,
      cost_price,
      sale_price,
      initial_quantity,
      perishable,
      shelf_life_days
    )
    VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    `,
    [
      product.product_id,
      product.name,
      product.category,
      product.cost_price,
      product.sale_price,
      product.initial_quantity,
      product.perishable,
      product.shelf_life_days,
    ]
  );
});

console.log("Products inserted");
db.close();